-- Capture run of script in file called monlib_schema_output.txt
set echo on
SPOOL monlib_schema_output.txt

-- Yiwei Chen
-- Assignment 1 - Database Design - Monash Library Services (MonLib)
-- Schema file

-- Added drop commands for sequences
DROP SEQUENCE branch_branch_code_seq;

DROP SEQUENCE author_aut_id_seq;

DROP SEQUENCE borrower_bor_no_seq;

DROP SEQUENCE loan_loan_no_seq;

DROP SEQUENCE manager_man_id_seq;

DROP SEQUENCE publisher_pub_id_seq;



-----------------------------------------------------
-- Generated by Oracle SQL Developer Data Modeler 17.4.0.355.2131
--   at:        2018-04-22 22:23:33 AEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP TABLE author CASCADE CONSTRAINTS;

DROP TABLE book CASCADE CONSTRAINTS;

DROP TABLE borrower CASCADE CONSTRAINTS;

DROP TABLE branch CASCADE CONSTRAINTS;

DROP TABLE class CASCADE CONSTRAINTS;

DROP TABLE copy CASCADE CONSTRAINTS;

DROP TABLE fine CASCADE CONSTRAINTS;

DROP TABLE isbn CASCADE CONSTRAINTS;

DROP TABLE loan CASCADE CONSTRAINTS;

DROP TABLE manager CASCADE CONSTRAINTS;

DROP TABLE publisher CASCADE CONSTRAINTS;

DROP TABLE reserve CASCADE CONSTRAINTS;

DROP TABLE return CASCADE CONSTRAINTS;

DROP TABLE subject CASCADE CONSTRAINTS;

DROP TABLE subjectbook CASCADE CONSTRAINTS;

DROP TABLE write CASCADE CONSTRAINTS;

CREATE TABLE author (
    aut_id     NUMBER(10) NOT NULL,
    aut_name   VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN author.aut_id IS
    'The id number of an author';

COMMENT ON COLUMN author.aut_name IS
    'The name of an author';

ALTER TABLE author ADD CONSTRAINT author_pk PRIMARY KEY ( aut_id );

CREATE TABLE book (
    book_callno        CHAR(20) NOT NULL,
    book_title         VARCHAR2(100) NOT NULL,
    book_discription   VARCHAR2(500) NOT NULL,
    book_pubdate       DATE NOT NULL,
    book_edtion        NUMBER(3) NOT NULL,
    book_pages         NUMBER(4) NOT NULL,
    book_language      CHAR(20) NOT NULL,
    book_isfiction     NUMBER(1) NOT NULL,
    book_difficult     NUMBER(2),
    book_notes         VARCHAR2(500),
    pub_id             NUMBER(7) NOT NULL
);

ALTER TABLE book
    ADD CHECK ( book_isfiction IN (
        0,
        1
    ) );

ALTER TABLE book
    ADD CONSTRAINT "Difficultiy levels" CHECK ( book_difficult IN (
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        21,
        22,
        23,
        24,
        25,
        26,
        27,
        28,
        29,
        30
    ) );

COMMENT ON COLUMN book.book_callno IS
    'The information held about a title is its Dewey Decimal call no (20 characters) - this call no is used to identify a particular title and for shelving books.'
;

COMMENT ON COLUMN book.book_title IS
    'The title of a book';

COMMENT ON COLUMN book.book_discription IS
    'The discription of a book';

COMMENT ON COLUMN book.book_pubdate IS
    'The publish date of a book';

COMMENT ON COLUMN book.book_edtion IS
    'The edtion of a book';

COMMENT ON COLUMN book.book_pages IS
    'The pages of a book';

COMMENT ON COLUMN book.book_language IS
    'The language of a book';

COMMENT ON COLUMN book.book_isfiction IS
    'A flag to distinguish fiction from reference';

COMMENT ON COLUMN book.book_difficult IS
    'reading difficultiy of a fiction';

COMMENT ON COLUMN book.book_notes IS
    'The notes of a book';

COMMENT ON COLUMN book.pub_id IS
    'The ID number of a publiser';

ALTER TABLE book ADD CONSTRAINT book_pk PRIMARY KEY ( book_callno );

CREATE TABLE borrower (
    bor_no           NUMBER(8) NOT NULL,
    bor_name         VARCHAR2(20) NOT NULL,
    bor_addno        NUMBER(5) NOT NULL,
    bor_road         VARCHAR2(50) NOT NULL,
    bor_city         VARCHAR2(50) NOT NULL,
    bor_state        VARCHAR2(50) NOT NULL,
    bor_country      VARCHAR2(50) NOT NULL,
    bor_homebranch   NUMBER(5) NOT NULL,
    bor_status       VARCHAR2(100) NOT NULL,
    class_name       VARCHAR2(20) NOT NULL,
    branch_code      NUMBER(5) NOT NULL
);

COMMENT ON COLUMN borrower.bor_no IS
    'Each borrower is identified by a borrower number';

COMMENT ON COLUMN borrower.bor_name IS
    'The name of  a borrower ';

COMMENT ON COLUMN borrower.bor_addno IS
    'The address number of a borrower';

COMMENT ON COLUMN borrower.bor_road IS
    'The road name of the address of aborrower';

COMMENT ON COLUMN borrower.bor_city IS
    'The city name of the address of a borrower';

COMMENT ON COLUMN borrower.bor_state IS
    'The state name of the address of a borrower';

COMMENT ON COLUMN borrower.bor_country IS
    'The country name of the address of a borrower';

COMMENT ON COLUMN borrower.bor_homebranch IS
    'The home branch number of a borrower ';

COMMENT ON COLUMN borrower.bor_status IS
    'The status(whether is flagged to prevent further borrowings ) of a borrower';

COMMENT ON COLUMN borrower.class_name IS
    'The name of borrower classification';

COMMENT ON COLUMN borrower.branch_code IS
    'For each branch Monash Library Services assigns a branch code';

ALTER TABLE borrower ADD CONSTRAINT borrower_pk PRIMARY KEY ( bor_no );

CREATE TABLE branch (
    branch_code      NUMBER(5) NOT NULL,
    branch_name      VARCHAR2(50) NOT NULL,
    branch_phone     NUMBER(10) NOT NULL,
    branch_addno     NUMBER(5) NOT NULL,
    branch_road      VARCHAR2(50) NOT NULL,
    branch_city      VARCHAR2(50) NOT NULL,
    branch_state     VARCHAR2(50) NOT NULL,
    branch_country   VARCHAR2(50) NOT NULL,
    man_id           NUMBER(7) NOT NULL
);

COMMENT ON COLUMN branch.branch_code IS
    'For each branch Monash Library Services assigns a branch code';

COMMENT ON COLUMN branch.branch_name IS
    'The name of a  library branch';

COMMENT ON COLUMN branch.branch_phone IS
    'The phone number of a libray branch';

COMMENT ON COLUMN branch.branch_addno IS
    'The address number of a library branch';

COMMENT ON COLUMN branch.branch_road IS
    'The road name of the address of a library branch';

COMMENT ON COLUMN branch.branch_city IS
    'The city name of the address of a library branch';

COMMENT ON COLUMN branch.branch_state IS
    'The state name of the address of a library branch';

COMMENT ON COLUMN branch.branch_country IS
    'The country name of the address of a library branch';

COMMENT ON COLUMN branch.man_id IS
    'Each manager is assigned a manger id';

ALTER TABLE branch ADD CONSTRAINT branch_pk PRIMARY KEY ( branch_code );

CREATE TABLE class (
    class_name        VARCHAR2(20) NOT NULL,
    class_numlimit    NUMBER(2) NOT NULL,
    class_timelimit   NUMBER(4) NOT NULL
);

COMMENT ON COLUMN class.class_name IS
    'The name of borrower classification';

COMMENT ON COLUMN class.class_numlimit IS
    'The limit of books can borrowe';

COMMENT ON COLUMN class.class_timelimit IS
    'how long can borrower borrowe a book';

ALTER TABLE class ADD CONSTRAINT class_pk PRIMARY KEY ( class_name );

CREATE TABLE copy (
    copy_barcode   VARCHAR2(25) NOT NULL,
    copy_status    VARCHAR2(100) NOT NULL,
    isbn_no        VARCHAR2(20) NOT NULL,
    branch_code    NUMBER(5) NOT NULL
);

COMMENT ON COLUMN copy.copy_barcode IS
    'each copy of a title is identified by a barcode';

COMMENT ON COLUMN copy.copy_status IS
    'availability (status)  of a copy';

COMMENT ON COLUMN copy.isbn_no IS
    'The ISBN number';

COMMENT ON COLUMN copy.branch_code IS
    'For each branch Monash Library Services assigns a branch code';

ALTER TABLE copy ADD CONSTRAINT copy_pk PRIMARY KEY ( copy_barcode );

CREATE TABLE fine (
    loan_no      NUMBER(10) NOT NULL,
    fine_amout   NUMBER(6) NOT NULL,
    fine_date    DATE
);

COMMENT ON COLUMN fine.loan_no IS
    'the unique number for each loan';

COMMENT ON COLUMN fine.fine_amout IS
    'the amount of the fine';

COMMENT ON COLUMN fine.fine_date IS
    'when the fine is paid';

ALTER TABLE fine ADD CONSTRAINT fine_pk PRIMARY KEY ( loan_no );

CREATE TABLE isbn (
    isbn_no       VARCHAR2(20) NOT NULL,
    isbn_type     VARCHAR2(20) NOT NULL,
    isbn_price    NUMBER(7,2) NOT NULL,
    book_callno   CHAR(20) NOT NULL,
    isbn_pages    NUMBER(4) NOT NULL
);

COMMENT ON COLUMN isbn.isbn_no IS
    'The ISBN number';

COMMENT ON COLUMN isbn.isbn_type IS
    'The book type of an ISBN (eg. hardcover, loose leaf, student edtion)';

COMMENT ON COLUMN isbn.isbn_price IS
    'The price of the book within one ISBN';

COMMENT ON COLUMN isbn.book_callno IS
    'The information held about a title is its Dewey Decimal call no (20 characters) - this call no is used to identify a particular title and for shelving books.'
;

COMMENT ON COLUMN isbn.isbn_pages IS
    'The pages of a book';

ALTER TABLE isbn ADD CONSTRAINT isbn_pk PRIMARY KEY ( isbn_no );

CREATE TABLE loan (
    loan_no           NUMBER(10) NOT NULL,
    loan_date         DATE NOT NULL,
    loan_returndate   DATE NOT NULL,
    bor_no            NUMBER(8) NOT NULL,
    copy_barcode      VARCHAR2(25) NOT NULL
);

COMMENT ON COLUMN loan.loan_no IS
    'the unique number for each loan';

COMMENT ON COLUMN loan.loan_date IS
    'The date of loan';

COMMENT ON COLUMN loan.loan_returndate IS
    'the calculated return date';

COMMENT ON COLUMN loan.bor_no IS
    'Each borrower is identified by a borrower number';

COMMENT ON COLUMN loan.copy_barcode IS
    'each copy of a title is identified by a barcode';

ALTER TABLE loan ADD CONSTRAINT loan_pk PRIMARY KEY ( loan_no );

ALTER TABLE loan
    ADD CONSTRAINT loan_un UNIQUE ( loan_date,
    copy_barcode,
    bor_no );

CREATE TABLE manager (
    man_id        NUMBER(7) NOT NULL,
    man_name      VARCHAR2(50) NOT NULL,
    man_phone     NUMBER(10) NOT NULL,
    branch_code   NUMBER(5) NOT NULL
);

COMMENT ON COLUMN manager.man_id IS
    'Each manager is assigned a manger id';

COMMENT ON COLUMN manager.man_name IS
    'The name of a manager';

COMMENT ON COLUMN manager.man_phone IS
    'The phone number of a manager';

COMMENT ON COLUMN manager.branch_code IS
    'For each branch Monash Library Services assigns a branch code';

CREATE UNIQUE INDEX manager__idx ON
    manager ( branch_code ASC );

ALTER TABLE manager ADD CONSTRAINT manager_pk PRIMARY KEY ( man_id );

CREATE TABLE publisher (
    pub_id        NUMBER(7) NOT NULL,
    pub_name      VARCHAR2(20) NOT NULL,
    pub_city      VARCHAR2(50) NOT NULL,
    pub_state     VARCHAR2(50) NOT NULL,
    pub_country   VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN publisher.pub_id IS
    'The ID number of a publiser';

COMMENT ON COLUMN publisher.pub_name IS
    'The name of  a publisher';

COMMENT ON COLUMN publisher.pub_city IS
    'The city name of the address of a publisher';

COMMENT ON COLUMN publisher.pub_state IS
    'The state name of the address of a publisher';

COMMENT ON COLUMN publisher.pub_country IS
    'The country name of the address of a publisher';

ALTER TABLE publisher ADD CONSTRAINT publisher_pk PRIMARY KEY ( pub_id );

CREATE TABLE reserve (
    bor_no         NUMBER(8) NOT NULL,
    res_date       DATE NOT NULL,
    res_time       DATE NOT NULL,
    copy_barcode   VARCHAR2(25) NOT NULL
);

COMMENT ON COLUMN reserve.bor_no IS
    'Each borrower is identified by a borrower number';

COMMENT ON COLUMN reserve.res_date IS
    'date of the reservation is made';

COMMENT ON COLUMN reserve.res_time IS
    'time of the reservation is made';

COMMENT ON COLUMN reserve.copy_barcode IS
    'each copy of a title is identified by a barcode';

ALTER TABLE reserve
    ADD CONSTRAINT reserve_pk PRIMARY KEY ( bor_no,
    copy_barcode,
    res_date );

CREATE TABLE return (
    loan_no   NUMBER(10) NOT NULL,
    re_date   DATE NOT NULL
);

COMMENT ON COLUMN return.loan_no IS
    'the unique number for each loan';

ALTER TABLE return ADD CONSTRAINT return_pk PRIMARY KEY ( loan_no );

CREATE TABLE subject (
    sub_name   VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN subject.sub_name IS
    'The name of a subject';

ALTER TABLE subject ADD CONSTRAINT subject_pk PRIMARY KEY ( sub_name );

CREATE TABLE subjectbook (
    book_callno   CHAR(20) NOT NULL,
    sub_name      VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN subjectbook.book_callno IS
    'The information held about a title is its Dewey Decimal call no (20 characters) - this call no is used to identify a particular title and for shelving books.'
;

COMMENT ON COLUMN subjectbook.sub_name IS
    'The name of a subject';

ALTER TABLE subjectbook ADD CONSTRAINT subjectbook_pk PRIMARY KEY ( book_callno,
sub_name );

CREATE TABLE write (
    book_callno   CHAR(20) NOT NULL,
    aut_id        NUMBER(10) NOT NULL
);

COMMENT ON COLUMN write.book_callno IS
    'The information held about a title is its Dewey Decimal call no (20 characters) - this call no is used to identify a particular title and for shelving books.'
;

COMMENT ON COLUMN write.aut_id IS
    'The id number of an author';

ALTER TABLE write ADD CONSTRAINT write_pk PRIMARY KEY ( book_callno,
aut_id );

ALTER TABLE book
    ADD CONSTRAINT book_publisher_fk FOREIGN KEY ( pub_id )
        REFERENCES publisher ( pub_id );

ALTER TABLE borrower
    ADD CONSTRAINT borrower_branch_fk FOREIGN KEY ( branch_code )
        REFERENCES branch ( branch_code );

ALTER TABLE borrower
    ADD CONSTRAINT borrower_class_fk FOREIGN KEY ( class_name )
        REFERENCES class ( class_name );

ALTER TABLE branch
    ADD CONSTRAINT branch_manager_fk FOREIGN KEY ( man_id )
        REFERENCES manager ( man_id );

ALTER TABLE copy
    ADD CONSTRAINT copy_branch_fk FOREIGN KEY ( branch_code )
        REFERENCES branch ( branch_code );

ALTER TABLE copy
    ADD CONSTRAINT copy_isbn_fk FOREIGN KEY ( isbn_no )
        REFERENCES isbn ( isbn_no );

ALTER TABLE fine
    ADD CONSTRAINT fine_loan_fk FOREIGN KEY ( loan_no )
        REFERENCES loan ( loan_no );

ALTER TABLE isbn
    ADD CONSTRAINT isbn_book_fk FOREIGN KEY ( book_callno )
        REFERENCES book ( book_callno );

ALTER TABLE loan
    ADD CONSTRAINT loan_borrower_fk FOREIGN KEY ( bor_no )
        REFERENCES borrower ( bor_no );

ALTER TABLE loan
    ADD CONSTRAINT loan_copy_fk FOREIGN KEY ( copy_barcode )
        REFERENCES copy ( copy_barcode );

ALTER TABLE manager
    ADD CONSTRAINT manager_branch_fk FOREIGN KEY ( branch_code )
        REFERENCES branch ( branch_code );

ALTER TABLE reserve
    ADD CONSTRAINT reserve_borrower_fk FOREIGN KEY ( bor_no )
        REFERENCES borrower ( bor_no );

ALTER TABLE reserve
    ADD CONSTRAINT reserve_copy_fk FOREIGN KEY ( copy_barcode )
        REFERENCES copy ( copy_barcode );

ALTER TABLE return
    ADD CONSTRAINT return_loan_fk FOREIGN KEY ( loan_no )
        REFERENCES loan ( loan_no );

ALTER TABLE subjectbook
    ADD CONSTRAINT subjectbook_book_fk FOREIGN KEY ( book_callno )
        REFERENCES book ( book_callno );

ALTER TABLE subjectbook
    ADD CONSTRAINT subjectbook_subject_fk FOREIGN KEY ( sub_name )
        REFERENCES subject ( sub_name );

ALTER TABLE write
    ADD CONSTRAINT write_author_fk FOREIGN KEY ( aut_id )
        REFERENCES author ( aut_id );

ALTER TABLE write
    ADD CONSTRAINT write_book_fk FOREIGN KEY ( book_callno )
        REFERENCES book ( book_callno );

CREATE SEQUENCE author_aut_id_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE borrower_bor_no_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE branch_branch_code_seq START WITH 100 NOCACHE ORDER;

CREATE SEQUENCE loan_loan_no_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE manager_man_id_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE publisher_pub_id_seq START WITH 1 NOCACHE ORDER;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            16
-- CREATE INDEX                             1
-- ALTER TABLE                             37
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          6
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
-----------------------------------------------------
set echo off
SPOOL off